api_platform:
    title: Hello API Platform
    version: 1.0.0
    mapping:
        paths:
            - '%kernel.project_dir%/src/Modules'
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
